# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0002_animal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
