# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0003_part_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='initiallycorrect',
            field=models.BooleanField(default=False),
        ),
    ]
