# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0004_part_initiallycorrect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['pk']},
        ),
    ]
