# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0006_auto_20180108_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='overwritten_sa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='overwritten_vol',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
