# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0008_auto_20180109_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='part',
            name='initiallycorrect',
        ),
        migrations.AddField(
            model_name='part',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Incorrect'), (1, 'Correct'), (2, 'Initially Correct')], default=0),
        ),
    ]
