# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0009_auto_20180110_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('edit_collection', 'Edit collection'),),
            },
        ),
        migrations.AlterField(
            model_name='part',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Incorrect'), (1, 'Corrected'), (2, 'Initially Correct')], default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal_app.Collection'),
        ),
    ]
