# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models


def create_default_collection(apps, schema_editor):
    Collection = apps.get_model("animal_app", "Collection")
    default = Collection(id=1,name="default")
    default.save()


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0009_auto_20180110_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('edit_collection', 'Edit collection'),),
            },
        ),
        migrations.AlterField(
            model_name='part',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Incorrect'), (1, 'Corrected'), (2, 'Initially Correct')], default=0),
        ),
        migrations.RunPython(create_default_collection),
    ]
