# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0010_auto_20180122_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': (('edit_animals', 'Edit animals'), ('view_animals', 'View animals'))},
        ),
        migrations.AddField(
            model_name='animal',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal_app.Collection'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='animal_app.Collection'),
        ),
    ]
