# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0011_auto_20180122_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shape',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='animal',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animal_app.Collection'),
        ),
        migrations.AlterField(
            model_name='part',
            name='overwritten_sa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Surface Area'),
        ),
        migrations.AlterField(
            model_name='part',
            name='overwritten_vol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Volume'),
        ),
    ]
