# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0012_auto_20180125_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['student', 'animal']},
        ),
    ]
